# Generated by Django 4.0.5 on 2022-06-23 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
