# Generated by Django 4.0.5 on 2022-07-08 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='speciality_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.staffspeciality'),
        ),
    ]
