# Generated by Django 4.0.5 on 2022-07-08 12:15

from django.db import migrations


def fill_staff_speciality(apps, schema_editor):
    staff = apps.get_model('users', 'Staff')
    staff_speciality = apps.get_model('users', 'StaffSpeciality')

    for staff_obj in staff.objects.all():
        staff_obj.speciality_fk, created = staff_speciality.objects.get_or_create(speciality='MD')
        staff_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_staffspeciality_userrole_staff_speciality_fk'),
    ]

    operations = [
        migrations.RunPython(fill_staff_speciality),
    ]
