# Generated by Django 4.0.5 on 2022-06-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('D', 'Doctor'), ('P', 'Patient'), ('N', 'Nurse')], max_length=15, null=True),
        ),
    ]
