# Generated by Django 4.0.5 on 2022-07-08 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220708_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='speciality',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='speciality_fk',
            new_name='speciality',
        ),
    ]
