# Generated by Django 4.0.5 on 2022-07-04 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_patientprescriptiondata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientPrescriptionData',
            new_name='Prescription',
        ),
    ]
