# Generated by Django 4.0.5 on 2022-07-08 13:25

from django.db import migrations


def fill_user_role(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    UserRole = apps.get_model('users', 'UserRole')

    for custom_user_obj in CustomUser.objects.all():
        custom_user_obj.role_fk, created = UserRole.objects.get_or_create(role='Doctor')
        custom_user_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customuser_role_fk'),
    ]

    operations = [
        migrations.RunPython(fill_user_role),
    ]
