# Generated by Django 4.0.5 on 2022-07-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20220708_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='role_fk',
            new_name='role',
        ),
    ]
