# Generated by Django 4.0.5 on 2022-07-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='time',
            field=models.TimeField(help_text='Please use that format:%H:%M....for example= 09:00'),
        ),
    ]
