# Generated by Django 4.0.5 on 2022-07-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_prescribemedicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.ManyToManyField(through='users.PrescribeMedicine', to='users.medicine'),
        ),
    ]
