# Generated by Django 4.0.5 on 2022-07-11 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_prescription_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='medicines',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='staff',
        ),
        migrations.DeleteModel(
            name='PrescribeMedicine',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
