# Generated by Django 4.0.5 on 2022-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
