# Generated by Django 4.0.5 on 2022-07-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_count_prescription_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('medicine_charge', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('room_charge', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('other_charge', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_paid', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
