# Generated by Django 4.0.5 on 2022-07-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='emergency_charge',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
