# Generated by Django 4.0.5 on 2022-07-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_bill_emergency_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
