# Generated by Django 4.0.5 on 2022-07-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_bill_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='other_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
