# Generated by Django 4.0.5 on 2022-07-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_alter_bill_total_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_charge',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
