# Generated by Django 4.0.5 on 2022-07-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_alter_bill_total_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Emergency',
        ),
    ]
