# Generated by Django 4.0.5 on 2022-07-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicine_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('room_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('emergency_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('other_charge', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
            ],
        ),
    ]
