# Generated by Django 4.0.5 on 2022-06-23 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_patient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslot', models.IntegerField(choices=[('09:00 – 09:30', '09:00 – 09:30'), ('10:00 – 10:30', '10:00 – 10:30'), ('11:00 – 11:30', '11:00 – 11:30'), ('12:00 – 12:30', '12:00 – 12:30'), ('13:00 – 13:30', '13:00 – 13:30'), ('14:00 – 14:30', '14:00 – 14:30'), ('15:00 – 15:30', '15:00 – 15:30'), ('16:00 – 16:30', '16:00 – 16:30'), ('17:00 – 17:30', '17:00 – 17:30')])),
                ('department', models.CharField(choices=[('MD Doctor', 'MD Doctor'), ('Pediatricians', 'Pediatricians'), ('Cardiologists', 'Cardiologists'), ('Neurologists', 'Neurologists'), ('surgeons', 'surgeons'), ('Orthopedic', 'Orthopedic')], max_length=50)),
                ('disease', models.CharField(max_length=300)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
