# Generated by Django 4.0.5 on 2022-07-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField()),
                ('AC', models.BooleanField(default=False)),
                ('is_ICU', models.BooleanField(default=False)),
                ('room_type', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('Semi-Private', 'Semi-Private')], max_length=100)),
            ],
        ),
    ]
