# Generated by Django 4.0.5 on 2022-07-08 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_bill'),
        ('appointment', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200)),
                ('in_date', models.DateField()),
                ('out_date', models.DateField(null=True)),
                ('charge', models.IntegerField(null=True)),
                ('is_bill_generated', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.room')),
            ],
        ),
        migrations.CreateModel(
            name='AdmitStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.admit')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
        migrations.AddField(
            model_name='admit',
            name='staff',
            field=models.ManyToManyField(through='appointment.AdmitStaff', to='users.staff'),
        ),
    ]
