# Generated by Django 4.0.5 on 2022-06-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointments_date_alter_appointments_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(help_text='Use that Format:YYYY-MM-DD'),
        ),
    ]
