# Generated by Django 4.0.5 on 2022-07-19 12:54

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_admit_admitstaff_admit_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admit',
            name='in_date',
            field=models.DateField(validators=[appointment.models.date_validation]),
        ),
    ]
