# Generated by Django 4.0.5 on 2022-06-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(help_text='Use that Format:YYYY-MM-DD...For example: 2022/6/26'),
        ),
    ]
