# Generated by Django 4.0.5 on 2022-06-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appointments_timeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('AC', models.BooleanField(default=False)),
                ('is_ICU', models.BooleanField(default=False)),
                ('room_type', models.CharField(choices=[('General', 'General'), ('Private', 'Private'), ('Semi-Private', 'Semi-Private')], max_length=100)),
            ],
        ),
    ]
