# Generated by Django 4.0.5 on 2022-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='timeslot',
            field=models.TimeField(),
        ),
    ]
