# Generated by Django 4.0.5 on 2022-06-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0012_alter_appointments_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='timeslot',
            field=models.CharField(max_length=200),
        ),
    ]
