# Generated by Django 4.0.5 on 2022-06-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_alter_appointments_timeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_no',
        ),
    ]
