# Generated by Django 4.0.5 on 2022-06-29 12:01

import appointment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_remove_room_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(validators=[appointment.models.date_validation]),
        ),
    ]
