# Generated by Django 4.0.5 on 2022-06-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_profile'),
        ('appointment', '0016_admit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmitMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admit', models.ManyToManyField(to='appointment.admit')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
    ]
