# Generated by Django 4.0.5 on 2022-06-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_admitmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admit',
            name='charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admit',
            name='out_date',
            field=models.DateField(null=True),
        ),
    ]
