# Generated by Django 4.0.5 on 2022-06-30 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_alter_admit_charge_alter_admit_out_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitmapping',
            name='admit',
        ),
        migrations.RemoveField(
            model_name='admitmapping',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Admit',
        ),
        migrations.DeleteModel(
            name='AdmitMapping',
        ),
    ]
