# Generated by Django 4.0.5 on 2022-06-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_profile'),
        ('appointment', '0019_remove_admitmapping_admit_remove_admitmapping_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_date', models.DateField()),
                ('out_date', models.DateField(null=True)),
                ('charge', models.IntegerField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.patient')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.room')),
                ('staff', models.ManyToManyField(to='users.staff')),
            ],
        ),
    ]
