# Generated by Django 4.0.5 on 2022-07-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NurseDuty',
        ),
    ]
